src/Entity/Player.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlayerRepository")
 */
class Player
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

  
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profilPic;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Team", inversedBy="players")
     */
    private $team;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contest", mappedBy="player", orphanRemoval=true)
     */
    private $contests;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tournament", inversedBy="players")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tournament;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contest", mappedBy="loser", orphanRemoval=true)
     */
    private $contestslose;

    public function __construct()
    {
        $this->contests = new ArrayCollection();
        $this->contestslose = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }


    public function getVictories() {

        $playerVictories = 0;

        foreach ($this->getContests() as $c) {
            $playerVictories += 1;
        }

        return $playerVictories;
    }


    public function setVictories(int $victories): self
    {
        $this->victories = $victories;

        return $this;
    }

   

    public function getScore() {

        $playerScore = 0;

        foreach ($this->getContests() as $c) {
            
            $playerScore += $c->getGame()->getVictoryValue();
        }

        return $playerScore;
    }

   

    public function getProfilPic(): ?string
    {
        return $this->profilPic;
    }

    public function setProfilPic(?string $profilPic): self
    {
        $this->profilPic = $profilPic;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    /**
     * @return Collection|Contest[]
     */
    public function getContests(): Collection
    {
        return $this->contests;
    }

    public function addContest(Contest $contest): self
    {
        if (!$this->contests->contains($contest)) {
            $this->contests[] = $contest;
            $contest->setPlayer($this);
            
        }

        return $this;
    }

    public function removeContest(Contest $contest): self
    {
        if ($this->contests->contains($contest)) {
            $this->contests->removeElement($contest);
            // set the owning side to null (unless already changed)
            if ($contest->getPlayer() === $this) {
                $contest->setPlayer(null);
            }
        }

        return $this;
    }

    public function getTournament(): ?Tournament
    {
        return $this->tournament;
    }

    public function setTournament(?Tournament $tournament): self
    {
        $this->tournament = $tournament;

        return $this;
    }

  
    public function getContestPlayed()
    {
        $won = 0;

        foreach ($this->getContests() as $c) {
           $won += 1;
        }

        $played = $won + $this->getLose();
        return $played;

    }


    public function getLose() 
    {
        $loses = 0;
        foreach ($this->getContestslose() as $c) {

            $loses += 1;
        }

        return $loses;
    }

    /**
     * @return Collection|Contest[]
     */
    public function getContestslose(): Collection
    {
        return $this->contestslose;
    }

    public function addContestslose(Contest $contestslose): self
    {
        if (!$this->contestslose->contains($contestslose)) {
            $this->contestslose[] = $contestslose;
            $contestslose->setLoser($this);
        }

        return $this;
    }

    public function removeContestslose(Contest $contestslose): self
    {
        if ($this->contestslose->contains($contestslose)) {
            $this->contestslose->removeElement($contestslose);
            // set the owning side to null (unless already changed)
            if ($contestslose->getLoser() === $this) {
                $contestslose->setLoser(null);
            }
        }

        return $this;
    }

    public function getPercentVictories()
    {

        if ($this->getContestPlayed() > 0) {

            $playerPercentVictories = $this->getVictories() * 100 / $this->getContestPlayed();

            return round($playerPercentVictories, 2) . "%";
        }

        else {
            return "/";
        }
       
    }

   

    
}

src/Form/PlayerType.php
<?php

namespace App\Form;

use App\Entity\Player;
use App\Entity\Team;
use App\Entity\Tournament;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;


class PlayerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pseudo')
            ->add('tournament', EntityType::class, [
                'class' => Tournament::class,
                'choice_label' => 'name',
            ]) 
            ->add('team', EntityType::class, [
                'class' => Team::class,
                'choice_label' => 'name',
            ]) 
            ->add('profilPic', FileType::class, [
                'mapped' => false,
                'label' => 'Add a picture',
                'required'   => false,
            ]);

        $builder->get('tournament')->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) {
                $form = $event->getForm();
                $data = $event->getForm()->getData();
                $teams = $data->getTeams();

                $form->getParent()->add('team', EntityType::class, [
                    'class' => Team::class,
                    'choices' => $teams,
                    'choice_label' => 'name',
                ]);
            }
        );    
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Player::class,
        ]);
    }
}

src/Controller/PlayerController.php
<?php

namespace App\Controller;

use App\Entity\Player;
use App\Form\PlayerType;
use App\Repository\PlayerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/player")
 */
class PlayerController extends AbstractController
{
    /**
     * @Route("/", name="player_index", methods={"GET"})
     */
    public function index(PlayerRepository $playerRepository): Response
    {
        return $this->render('player/index.html.twig', [
            'players' => $playerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="player_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $player = new Player();
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /**********************************************************************/

            //retrive the file send in the request
            $file = $request->files->get('player')['profilPic'];

            //put the path to the folder that will stock our files in a var
            $uploads_player_directory = $this->getParameter('uploads_player_directory');

            //create a var to change the name of the file
            $filename = md5(uniqid()) . '.' . $file->guessExtension();

            //move the file into the folder
            $file->move(
                $uploads_player_directory,
                $filename
            );

            //set the event photo's attribut
            $post = $player->setProfilPic($filename);

            /**********************************************************************/      


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($player);
            $entityManager->flush();

            return $this->redirectToRoute('player_index');
        }

        return $this->render('player/new.html.twig', [
            'player' => $player,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="player_show", methods={"GET"})
     */
    public function show(Player $player): Response
    {
        return $this->render('player/show.html.twig', [
            'player' => $player,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="player_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Player $player): Response
    {
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /**********************************************************************/

            //retrive the file send in the request
            $file = $request->files->get('player')['profilPic'];

            //put the path to the folder that will stock our files in a var
            $uploads_player_directory = $this->getParameter('uploads_player_directory');

            //create a var to change the name of the file
            $filename = 'player' . md5(uniqid()) . '.' . $file->guessExtension();

            //move the file into the folder
            $file->move(
                $uploads_player_directory,
                $filename
            );

            //set the event photo's attribut
            $player->setProfilPic($filename);

            /**********************************************************************/ 
            
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('player_show', [
                'id' => $player->getId(),
            ]);
        }

        return $this->render('player/edit.html.twig', [
            'player' => $player,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="player_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Player $player): Response
    {

        $tournament = $player->getTournament();

        if ($this->isCsrfTokenValid('delete'.$player->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($player);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tournament_show', [
            'id' => $tournament->getId(),
        ]);
    }
}

templates/player/_delete_form.html.twig
<form method="post" action="{{ path('player_delete', {'id': player.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ player.id) }}">
    <button class="btn btn-danger delete-btn">Delete</button>
</form>

templates/player/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Player{% endblock %}

{% block body %}
    

    {# {{ include('player/_form.html.twig', {'button_label': 'Update'}) }} #}

         <h3 class="add-title">Edit player : </h3>
         {{ form_start(form) }}
         <div class="add-input">{{ form_label(form.pseudo, 'Pseudo') }}</div>
         {{ form_widget(form.pseudo, {'attr': {'class': 'form-control add-input' }}) }}
         {{ form_row(form.pseudo) }}

         <div class="add-input">{{ form_label(form.team, 'Team') }}</div>
         {{ form_widget(form.team, {'attr': {'class': 'form-control add-input' }}) }}
         {{ form_row(form.team) }}

         <div class="add-input">{{ form_label(form.profilPic, 'Player Pic') }}</div>
         <div class="add-input">
             <button type="button" id="add-player-edit-file" class="btn btn-success btn-pic">Chose a pic</button>
             <span id="custom-player-edit-text">No file chosen, yet</span>
         </div>


         <div class="hide-btn">
             {{ form_label(form.profilPic, 'chose photo') }}
             {{ form_widget(form.profilPic, {'attr': {'class': 'form-control ppp', 'id': 'ppp'} }) }}
             {{ form_row(form.profilPic) }}
         </div>
         <div class="add-input sub-btn">
             <button type="submit" class="btn btn-success btn-add">Edit</button>
         </div>

         {{ form_end(form) }}
     

         <script>
             document.getElementById('add-player-edit-file').addEventListener('click', function () {
                 document.getElementById('player_profilPic').click();
             });
             document.getElementById('player_profilPic').addEventListener("change", function () {
                 if (document.getElementById('player_profilPic').value) {
                     document.getElementById('custom-player-edit-text').innerHTML = document.getElementById(
                         'player_profilPic').value.match(/[\/\\]([\w\d\s\.\-\(\)]+)$/)[1];
                 } else {
                     document.getElementById('custom-player-edit-text').innerHTML = "No file chosen, yet";
                 }
             });
</script>
{% endblock %}

templates/player/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player index{% endblock %}

{% block body %}
    <h1>Player index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pseudo</th>
                <th>Victories</th>
                <th>Score</th>
                <th>ProfilPic</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td>{{ player.id }}</td>
                <td>{{ player.pseudo }}</td>
                <td>{{ player.victories }}</td>
                <td>{{ player.score }}</td>
                <td>{{ player.profilPic }}</td>
                <td>
                    <a href="{{ path('player_show', {'id': player.id}) }}">show</a>
                    <a href="{{ path('player_edit', {'id': player.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('player_new') }}">Create new</a>
{% endblock %}

templates/player/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Player{% endblock %}

{% block body %}
    <h1>Create new Player</h1>

    {{ include('player/_form.html.twig') }}

    <a href="{{ path('player_index') }}">back to list</a>
{% endblock %}

templates/player/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player{% endblock %}

{% block body %}
    
    <div class="container">
        <div class="head-profil">
            <img class="pic-profil"
                {% if player.getProfilPic() == null %}src="{{ asset('dist/images/player/unknown.png')}}"
                {% endif %} src="{{ asset('dist/images/player/' ~ player.getProfilPic()) }}">
            <div class="head-info">
                <p class="infos info-player">{{ player.pseudo}}</p>
                <p class="infos info-team"><a
                        href="{{ path('team_show',   {'id': player.team.id}) }}">{{ player.team.name}}</p>
                <div class="edit-button flex-container">
                    <div id="player-edit-btn" class="edit-team btn btn-success create-btn"><a class="link-button"
                            href="{{ path('player_edit',       {'id': player.id}) }}">edit player</a></div>
                    {{ include('player/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>

    <hr><br>
    <div class="container">   

        <h3 class="resume-title">Resume: </h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Score</th>
                    <th>Victories</th>
                    <th>Loses</th>
                    <th>Played</th>
                    <th>Team Score</th>
                    <th>Percent Victories</th>
                </tr>
            </thead>
            <tr>
                <td class="tournament-show">{{ player.score }}</td>
                <td class="tournament-show">{{ player.victories }}</td>
                <td class="tournament-show">{{ player.lose }}</td>
                <td class="tournament-show">{{player.contestPlayed}}</td>
                <td class="tournament-show">{{ player.team.score }}</td>
                <td class="tournament-show">{{ player.getPercentVictories()}}</td>
        </table>



        <h3 class="resume-title">Past Wins :</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Winner</th>
                    <th>Loser</th>
                    <th>Game</th>
                    <th>Points</th>
                    

                </tr>
            </thead>
            {% for contest in player.contests %}
            <tr>
                <td class="tournament-show">{{ contest.createdAt | date('d/m/Y à H:i') }}</td>
                <td class="tournament-show"><a
                        href="{{ path('player_show',   {'id': contest.player.id}) }}">{{ contest.player.pseudo}}</a></td>
                <td class="tournament-show"><a
                        href="{{ path('player_show',   {'id': contest.loser.id}) }}">{{ contest.loser.pseudo }}</a></td>
                <td class="tournament-show"><a
                        href="{{ path('game_show',   {'id': contest.game.id}) }}">{{ contest.game.name }}</td>
                <td class="tournament-show">{{ contest.game.victoryValue }}</td>
                
                
    {% endfor %}
    </table>


    <h3 class="resume-title">Past loses :</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Winner</th>
                <th>Loser</th>
                <th>Game</th>
                <th>Points</th>
                

            </tr>
        </thead>
        {% for contest in player.contestslose %}
        <tr>
            <td class="tournament-show">{{ contest.createdAt | date('d/m/Y à H:i') }}</td>
            <td class="tournament-show"><a
                    href="{{ path('player_show',   {'id': contest.player.id}) }}">{{ contest.player.pseudo}}</a></td>
            <td class="tournament-show"><a
                    href="{{ path('player_show',   {'id': contest.loser.id}) }}">{{ contest.loser.pseudo }}</a></td>
            <td class="tournament-show"><a href="{{ path('game_show',   {'id': contest.game.id}) }}">{{ contest.game.name }}</a>
            </td>
            <td class="tournament-show">{{ contest.game.victoryValue }}</td>
            

            {% endfor %}
    </table>
    </div>
    
{% endblock %}