src/Entity/Game.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GameRepository")
 */
class Game
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $victoryValue;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contest", mappedBy="game", orphanRemoval=true)
     */
    private $contests;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tournament", inversedBy="games")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tournament;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Photo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $rules;

    public function __construct()
    {
        $this->contests = new ArrayCollection();
        $this->rules = "No rules enter, yet";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getVictoryValue(): ?int
    {
        return $this->victoryValue;
    }

    public function setVictoryValue(int $victoryValue): self
    {
        $this->victoryValue = $victoryValue;

        return $this;
    }

    /**
     * @return Collection|Contest[]
     */
    public function getContests(): Collection
    {
        return $this->contests;
    }

    public function addContest(Contest $contest): self
    {
        if (!$this->contests->contains($contest)) {
            $this->contests[] = $contest;
            $contest->setGame($this);
        }

        return $this;
    }

    public function removeContest(Contest $contest): self
    {
        if ($this->contests->contains($contest)) {
            $this->contests->removeElement($contest);
            // set the owning side to null (unless already changed)
            if ($contest->getGame() === $this) {
                $contest->setGame(null);
            }
        }

        return $this;
    }

    public function getTournament(): ?Tournament
    {
        return $this->tournament;
    }

    public function setTournament(?Tournament $tournament): self
    {
        $this->tournament = $tournament;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(?string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }

    public function getPlayed(): ?int {
        $played = 0;
        foreach ($this->getContests() as $c) {

            if ($c->getGame()->getId() == $this->id ) {
            $played += 1;
            }
        }
        return $played;
    }

    public function getRules(): ?string
    {
        return $this->rules;
    }

    public function setRules(?string $rules): self
    {
        $this->rules = $rules;

        return $this;
    }
}

src/Entity/Team.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TeamRepository")
 */
class Team
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

   
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Player", mappedBy="team", orphanRemoval=true)
     */
    private $players;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tournament", inversedBy="teams")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tournament;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    public function __construct()
    {
        $this->players = new ArrayCollection();
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }


    /**
     * @return Collection|Player[]
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(Player $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players[] = $player;
            $player->setTeam($this);
        }

        return $this;
    }

    public function removePlayer(Player $player): self
    {
        if ($this->players->contains($player)) {
            $this->players->removeElement($player);
            // set the owning side to null (unless already changed)
            if ($player->getTeam() === $this) {
                $player->setTeam(null);
            }
        }

        return $this;
    }

    public function getTournament(): ?Tournament
    {
        return $this->tournament;
    }

    public function setTournament(?Tournament $tournament): self
    {
        $this->tournament = $tournament;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getScore(): ?int {
        $tScore = 0;
        foreach ($this->getPlayers() as $p) {
            $tScore += $p->getScore();
        }
        return $tScore;
    }

    public function getVictories(): ?int
    {
        $tVictories = 0;
        foreach ($this->getPlayers() as $p) {
            $tVictories += $p->getVictories();
        }
        return $tVictories;
    }

    public function getLose(): ?int
    {
        $tLoses = 0;
        foreach ($this->getPlayers() as $p) {
            $tLoses += $p->getLose();
        }
        return $tLoses;
    }

    public function getPlayed(): ?int
    {
        $tPlayed = 0;
        foreach ($this->getPlayers() as $p) {
            $tPlayed += $p->getContestPlayed();
        }
        return $tPlayed;
    }

    public function getPercentVictories()
    {

        if($this->getPlayed() > 0) {

            $teamPercentVictories = $this->getVictories() * 100 / $this->getPlayed();
            return round($teamPercentVictories, 2) . "%";
        } else {
            return "/";
        }
        
    }

    public function allExceptThis(Team $team) {
        
        $teams = $team->getTournament()->getTeams();
        $availablePlayers = [];

        foreach ($teams as $t) {
            if ($t != $team) {

                foreach ($t->getPlayers() as $p) {
                    array_push($availablePlayers, $p);
                }
            }
        }
         return $availablePlayers;
    }

    public function thisTournamentTeam(Team $team)
    {
        $teams = $team->getTournament()->getTeams();

        return $teams;
    }
   
   
}

src/Form/TournamentType.php
<?php

namespace App\Form;

use App\Entity\Tournament;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TournamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tournament::class,
        ]);
    }
}

src/Controller/TournamentController.php
<?php

namespace App\Controller;

use App\Entity\Tournament;
use App\Entity\Team;
use App\Entity\Player;
use App\Entity\Game;
use App\Entity\Contest;
use App\Form\TournamentType;
use App\Form\TeamType;
use App\Form\PlayerType;
use App\Form\GameType;
use App\Form\ContestType;
use App\Repository\TournamentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Doctrine\Common\Persistence\ObjectManager;


/**
 * @Route("/tournament")
 */
class TournamentController extends AbstractController
{
    /**
     * @IsGranted("ROLE_USER")
     * @Route("/", name="tournament_index", methods={"GET", "POST"})
     */
    public function index(TournamentRepository $tournamentRepository, Request $request): Response
    {

        $usr = $this->getUser();
        $isUser = isset($usr);
        $tournament = new Tournament();
        $form = $this->createForm(TournamentType::class, $tournament);

        //retieve the id of the current user
        $actualUser = $this->getUser();
        //set the organizer with the current user
        $tournament->setOrganizer($actualUser);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tournament);
            $entityManager->flush();

            return $this->redirectToRoute('tournament_index');
        }
        
    
        return $this->render('tournament/index.html.twig', [
            'tournaments' => $usr->getTournament(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/new", name="tournament_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {

        
        $tournament = new Tournament();
        $form = $this->createForm(TournamentType::class, $tournament);

        //retieve the id of the current user
        $actualUser = $this->getUser();
        //set the organizer with the current user
        $tournament->setOrganizer($actualUser);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tournament);
            $entityManager->flush();

            return $this->redirectToRoute('tournament_index');
        }

        return $this->render('tournament/new.html.twig', [
            'tournament' => $tournament,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tournament_show", methods={"GET", "POST"})
     */
    public function show(Tournament $tournament, Request $request, ObjectManager $manager): Response
    {

        // get the actual user to make sure the user only see his tournaments

        $usr = $this->getUser();
        $usrId = $this->getUser()->getId();
        $organizerId = $tournament->getOrganizer()->getId();

       

        if ($usrId == $organizerId){

            //Add team's form    
            $team = new Team();
            $teamForm = $this->createForm(TeamType::class, $team);
            $teamForm->handleRequest($request);


            if ($teamForm->isSubmitted() && $teamForm->isvalid()) {

                /**********************************************************************/

                //retrive the file send in the request
                $file = $request->files->get('team')['photo'];

                //put the path to the folder that will stock our files in a var
                $uploads_team_directory = $this->getParameter('uploads_team_directory');

                //create a var to change the name of the file
                $filename = 'team' . md5(uniqid()) . '.' . $file->guessExtension();

                //move the file into the folder
                $file->move(
                    $uploads_team_directory,
                    $filename
                );

                //set the event photo's attribut
                $team->setPhoto($filename);

                /**********************************************************************/     

                $team->setTournament($tournament);

                $manager->persist($team);
                $manager->flush();

                return $this->redirectToRoute('tournament_show', [
                    'id' => $tournament->getId()
                ]);
            }

            //Add player's form 
            $player = new Player();
            $playerForm = $this->createForm(PlayerType::class, $player);
            $playerForm->handleRequest($request);

            

            if($playerForm->isSubmitted() && $playerForm->isValid()) {

                /**********************************************************************/

                

                //retrive the file send in the request
                $file = $request->files->get('player')['profilPic'];

                if ($file === null) {
                    $player->setProfilPic(null);
                } 

                else {

                    //put the path to the folder that will stock our files in a var
                    $uploads_player_directory = $this->getParameter('uploads_player_directory');

                    //create a var to change the name of the file
                    $filename = 'player' . md5(uniqid()) . '.' . $file->guessExtension();

                    //move the file into the folder
                    $file->move(
                        $uploads_player_directory,
                        $filename
                    );

                    //set the event photo's attribut
                    $player->setProfilPic($filename);

                }

                

                /**********************************************************************/ 

                

                $manager->persist($player);
                $manager->flush();

                return $this->redirectToRoute('tournament_show', [
                    'id' => $tournament->getId()
                ]);
            }

            //Add game's form 
            $game = new Game();
            $gameForm = $this->createForm(GameType::class, $game);
            $gameForm->handleRequest($request);

            if ($gameForm->isSubmitted() && $gameForm->isValid()) {

                /**********************************************************************/

                //retrive the file send in the request
                $file = $request->files->get('game')['photo'];

                //put the path to the folder that will stock our files in a var
                $uploads_game_directory = $this->getParameter('uploads_game_directory');

                //create a var to change the name of the file
                $filename = 'game' . md5(uniqid()) . '.' . $file->guessExtension();

                //move the file into the folder
                $file->move(
                    $uploads_game_directory,
                    $filename
                );

                //set the event photo's attribut
                $game->setPhoto($filename);

                /**********************************************************************/   

                $game->setTournament($tournament);

                $manager->persist($game);
                $manager->flush();

                return $this->redirectToRoute('tournament_show', [
                    'id' => $tournament->getId()
                ]);
            }

            //Add contest's form 
            $contest = new Contest();
            $contestForm = $this->createForm(ContestType::class, $contest);
            $contestForm->handleRequest($request);

            if ($contestForm->isSubmitted() && $contestForm->isValid()) {

                $contest->setTournament($tournament);
        
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($contest);
                $entityManager->flush();

                $manager->persist($contest);
                $manager->flush();

                return $this->redirectToRoute('tournament_show', [
                    'id' => $tournament->getId()
                ]);
            }


        return $this->render('tournament/show.html.twig', [
            'tournament'   => $tournament,
            'teamForm'     => $teamForm->createView(),
            'playerForm'   => $playerForm->createView(),
            'gameForm'     => $gameForm->createView(),
            'contestForm'  => $contestForm->createView()
        ]);
        }

        else {
            return $this->render('tournament/index.html.twig', [
                'tournaments' => $usr->getTournament(),
            ]);

        }
    }

    /**
     * @Route("/{id}/edit", name="tournament_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tournament $tournament): Response
    {
        $form = $this->createForm(TournamentType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('tournament_index', [
                'id' => $tournament->getId(),
            ]);
        }

        return $this->render('tournament/edit.html.twig', [
            'tournament' => $tournament,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tournament_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tournament $tournament): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tournament->getId(), $request->request->get('_token'))) {

templates/tournament/_delete_form.html.twig
<form method="post" action="{{ path('tournament_delete', {'id': tournament.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournament.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tournament/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tournament{% endblock %}

{% block body %}
    <h1>Edit Tournament</h1>

    {{ include('tournament/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('tournament_index') }}">back to list</a>

    {{ include('tournament/_delete_form.html.twig') }}
{% endblock %}

templates/tournament/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tournament{% endblock %}

{% block body %}
    <h1>Create new Tournament</h1>

    <div class="bg-modal player-modal">
        <div class="modal-content">

            <h3 class="add-title">Name : </h3>
            {{ form_start(form) }}
            <div class="add-input">{{ form_label(form.name, 'Name') }}</div>
            {{ form_widget(form.name, {'attr': {'class': 'form-control add-input' }}) }}
            {{ form_row(form.name) }}

            
            <div class="add-input sub-btn">
                <button type="submit" class="btn btn-success btn-add">Create</button>
            </div>

            {{ form_end(form) }}
        </div>
    </div>

    {{ include('tournament/_form.html.twig') }}

    <a href="{{ path('tournament_index') }}">back to list</a>
{% endblock %}

templates/tournament/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournament{% endblock %}

{% block body %}
<div class="container">


    {# ----------TEAMS BOARD---------- #}
    <div id="tournament-head">
        <div id="team-btn" class="btn btn-success create-btn">+</div>
    </div>
    <table class="table" >
        <thead>
            <tr>
                <th>Teams</i></th>
                <th>Name <i class="fas fa-caret-down"></i></th>
                <th>Players <i class="fas fa-caret-down"></i></th>
                <th>Victories <i class="fas fa-caret-down"></i></th>
                <th>Score <i class="fas fa-caret-down"></i></th>
            </tr>
        </thead>
        {% for team in tournament.teams %}
        <tr>
            <td><img class="team-pic" src="{{ asset('dist/images/team/' ~ team.getPhoto()) }}"></td>
            <td class="tournament-show"><a href="{{ path('team_show',   {'id': team.id}) }}"> {{ team.name }}</a></td>
            <td class="tournament-show" id="list-players">{% for player in team.players %}
                <a href="{{ path('player_show',   {'id': player.id}) }}">{{ player.pseudo }}</a>
                {% endfor %}
            </td>
            <td class="tournament-show">{{ team.getVictories() }}</td>
            <td class="tournament-show">{{ team.getScore() }}</td>
            {# <td></td> #}
        </tr>
        {% endfor %}
    </table>


    {# ----------PLAYERS BOARD---------- #}
    <br>
    <div id="tournament-head">
        <a href="#body">
            <div id="player-btn" class="btn btn-success create-btn">+</div>
        </a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Players</th>
                <th>Name <i class="fas fa-caret-down"></i></th>
                <th>Team <i class="fas fa-caret-down"></i></th>
                <th>Victories <i class="fas fa-caret-down"></i></th>
                <th>Score <i class="fas fa-caret-down"></i></th>
            </tr>
        </thead>
        {% for team in tournament.teams %}
        {% for player in team.players %}
        <tr>
            <td><img class="player-pic"
                    {% if player.getProfilPic() == null %}src="{{ asset('dist/images/player/unknown.png')}}"{% endif %}
                    src="{{ asset('dist/images/player/' ~ player.getProfilPic()) }}"></td>
            <td class="tournament-show"><a href="{{ path('player_show',   {'id': player.id}) }}">{{ player.pseudo }}</a>
            </td>
            <td class="tournament-show"><a href="{{ path('team_show',   {'id': team.id}) }}"> {{ player.team.name }}</a></td>
            <td class="tournament-show">{{ player.victories }}</td>
            <td class="tournament-show">{{ player.score }}</td>
        </tr>
        {% endfor %}
        {% endfor %}
    </table>

    {# ----------GAMES BOARD---------- #}

    <br>
    <div id="tournament-head">
        <a href="#body">
            <div id="game-btn" class="btn btn-success create-btn">+</div>
        </a>    
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Game</th>
                <th>Name <i class="fas fa-caret-down"></i></th>
                <th>Value <i class="fas fa-caret-down"></i></th>
                <th>Played <i class="fas fa-caret-down"></i></th>
            </tr>
        </thead>
        {% for game in tournament.games %}
        <tr>
            <td class="tournament-show"><img class="game-pic" src="{{ asset('dist/images/game/' ~ game.getPhoto()) }}">
            </td>
            <td class="tournament-show"><a href="{{ path('game_show',   {'id': game.id}) }}">{{ game.name }}</a></td>
            <td class="tournament-show">{{ game.victoryValue }} pts</td>
            <td class="tournament-show">{{ game.getPlayed() }}</td>
        </tr>
        {% endfor %}
    </table>


    {# ----------CONTESTS BOARD---------- #}
    <br>
    <div id="tournament-head">
        <a class"scroll-up" href="#body">
            <div id="contest-btn" class="btn btn-success create-btn">+</div>
        </a>    
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Winner <i class="fas fa-caret-down"></i></th>
                <th>Loser <i class="fas fa-caret-down"></i></th>
                <th>Game <i class="fas fa-caret-down"></i></th>
                <th>Points <i class="fas fa-caret-down"></i></th>
                <th>Options <i class="fas fa-caret-down"></i></th>
            </tr>
        </thead>
        {% for contest in tournament.contests %}
        <tr>
            <td class="tournament-show">{{ contest.createdAt | date('d/m/Y à H:i') }}</td>
            <td class="tournament-show">{{ contest.player.pseudo}}</td>
            <td class="tournament-show">{{ contest.loser.pseudo }}</td>
            <td class="tournament-show">{{ contest.game.name }}</td>
            <td class="tournament-show">{{ contest.game.victoryValue }}</td>
            <td>
                <div class="edit-btn">
                    {{ include('contest/_delete_form.html.twig') }}
                </div>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>



<!-- ________________________________________________________MODAL SECTION_______________________________________________________________________ -->

<!-- ___________Team Modal___________ -->
<div class="bg-modal team-modal">
    <div class="modal-content">
        <div class="close-team">
            +
        </div>
        <h3 class="add-title">Add a team: </h3>
        {{ form_start(teamForm) }}
        <div class="add-input">{{ form_label(teamForm.name, 'Name') }}</div>
        {{ form_widget(teamForm.name, {'attr': {'class': 'form-control add-input' }}) }}
        {{ form_row(teamForm.name) }}

        <div class="add-input">{{ form_label(teamForm.photo, 'Team Pic') }}</div>
        <div class="add-input">
            <button type="button" id="add-file" class="btn btn-success btn-pic">Chose a pic</button>
            <span id="custom-text">No file chosen, yet</span>
        </div>
         
        <div class="hide-btn">
            {{ form_label(teamForm.photo, 'chose photo') }}
            {{ form_widget(teamForm.photo, {'attr': {'class': 'form-control' }}) }}
            {{ form_row(teamForm.photo) }}
        </div>

         <div class="add-input sub-btn">
             <button type="submit" class="btn btn-success btn-add">Create team</button>
         </div>
        
        {{ form_end(teamForm) }}
    </div>
</div>



<!-- __________Player Modal__________ -->

<div class="bg-modal player-modal">
    <div class="player-modal-content modal-content">
        <div class="close-player">
            +
        </div>
        <h3 class="add-title">Add a player : </h3>
            {{ form_start(playerForm) }}
            <div class="add-input">{{ form_label(playerForm.pseudo, 'Pseudo') }}</div>
            {{ form_widget(playerForm.pseudo, {'attr': {'class': 'form-control add-input' }}) }}
            {{ form_row(playerForm.pseudo) }}

            <div class="add-input">{{ form_label(playerForm.tournament, 'Tournament') }}</div>
            {{ form_widget(playerForm.tournament, {'attr': {'class': 'form-control add-input' }}) }}
            {{ form_row(playerForm.tournament) }}
            
            <div class="add-input">{{ form_label(playerForm.team, 'Team') }}</div>
            {{ form_widget(playerForm.team, {'attr': {'class': 'form-control add-input' }}) }}
            {{ form_row(playerForm.team) }}
            

            <div class="add-input">{{ form_label(playerForm.profilPic, 'Player Pic') }}</div>
            <div class="add-input">
                <button type="button" id="add-player-file" class="btn btn-success btn-pic">Chose a pic</button>
                <span id="custom-player-text">No file chosen, yet</span>
            </div>


            <div class="hide-btn">
                {{ form_label(playerForm.profilPic, 'chose photo') }}
                {{ form_widget(playerForm.profilPic, {'attr': {'class': 'form-control' }}) }}
                {{ form_row(playerForm.profilPic) }}
            </div>
            <div class="add-input sub-btn">
                <button type="submit" class="btn btn-success btn-add">Créer</button>
            </div>
            
            {{ form_end(playerForm) }}
    </div>
</div>



<!-- __________Game Modal__________ -->

<div class="bg-modal game-modal">
    <div class="modal-content">
        <div class="close-game">
            +
        </div>
        <h3 class="add-title">Add a game : </h3>
            {{ form_start(gameForm) }}

            <div class="add-input">{{ form_label(gameForm.name, 'Name') }}</div>
            {{ form_widget(gameForm.name, {'attr': {'class': 'form-control add-input' }}) }}
            {{ form_row(gameForm.name) }}

            <div class="add-input">{{ form_label(gameForm.victoryValue, 'Victory value') }}</div>
            {{ form_widget(gameForm.victoryValue, {'attr': {'class': 'form-control add-input' }}) }}
            {{ form_row(gameForm.victoryValue) }}

             <div class="add-input">{{ form_label(gameForm.photo, 'Game Pic') }}</div>
             <div class="add-input">
                 <button type="button" id="add-game-file" class="btn btn-success btn-pic">Chose a pic</button>
                 <span id="custom-game-text">No file chosen, yet</span>
             </div>


             <div class="hide-btn">
                 {{ form_label(gameForm.photo, 'chose photo') }}
                 {{ form_widget(gameForm.photo, {'attr': {'class': 'form-control' }}) }}
                 {{ form_row(gameForm.photo) }}
             </div>

            <div class="add-input sub-btn">
                <button type="submit" class="btn btn-success btn-add">Créer</button>
            </div>    
            {{ form_end(gameForm) }}
    </div>
</div>



<!-- __________Contest Modal__________ -->
<div class="bg-modal contest-modal">
    <div class="modal-content">
        <div class="close-contest">
            +
        </div>
        <h3 class="add-title">Add a contest : </h3>
            {{ form_start(contestForm) }}

            <div class="add-input">{{ form_label(contestForm.player, 'Winner') }}</div>
            {{ form_widget(contestForm.player, {'attr': {'class': 'form-control add-input' }}) }}
            {{ form_row(contestForm.player) }}

            <div class="add-input">{{ form_label(contestForm.loser, 'Loser') }}</div>
            {{ form_widget(contestForm.loser, {'attr': {'class': 'form-control add-input' }}) }}
            {{ form_row(contestForm.loser) }}


            <div class="add-input">{{ form_label(contestForm.game, 'Game') }}</div>
            {{ form_widget(contestForm.game, {'attr': {'class': 'form-control add-input' }}) }}
            {{ form_row(contestForm.game) }}

            <div class="add-input sub-btn">
                <button type="submit" class="btn btn-success">Créer</button>
            </div>
            
            {{ form_end(contestForm) }}
    </div>
</div>

<script>
 
</script>


{% endblock %}